export const skillsArray: [string, boolean][] = [
	["Javascript", true],
	["Typescript", true],
	["Python", true],
	["SQL", false],
	["Bash", false],
	["HTML", true],
	["CSS", true],
	["Sass", false],
	["SCSS", true],
	["Node", true],
	["React", true],
	["Vue", false],
	["Express", true],
	["Flask", false],
	["Nest.JS", true],
	["Next", false],
	["Electron", false],
	["PostgreSQL", true],
	["Presto", false],
	["Git", true],
	["Github", true],
	["Heroku", true],
	["Netlify", true],
	["AWS", false],
	["Jira", true],
	["Splunk", false],
	["Redash", false],
	["Trello", true],
	["Twilio", true],
	["Sendgrid", true],
	["Postman", true],
	["EmailJS", false],
	["Vite", true],
	["REST", true],
	["Agile", true],
	["Scrum", false],
	["OOP", true],
	["TDD", false],
	["Jest", false],
	["Cypress", false],
	["Knex", false],
	["Objection", false],
	["TypeORM", true],
	["Prisma", false],
	["Cheerio", false],
	["Axios", true],
	["Linux", true],
	["Windows", true],
	["Mac", true],
	["Microsoft Office", false],
	["Google Suite", false],
	["VS Code", true],
	["VIM", false],
	["Mac/Linux Terminal", true],
	["PowerShell", false],
]
