export const skillsArray: [string, boolean, boolean][] = [
	["Javascript", true, true],
	["Typescript", true, true],
	["Python", true, false],
	["SQL", false, false],
	["Bash", false, false],
	["HTML", true, true],
	["CSS", true, false],
	["Sass", false, false],
	["SCSS", true, true],
	["Node", true, false],
	["React", true, true],
	["Vue", false, false],
	["Express", true, false],
	["Flask", false, false],
	["Nest.JS", true, true],
	["Next", false, false],
	["Electron", false, false],
	["PostgreSQL", true, false],
	["Presto", false, false],
	["Git", true, true],
	["Github", true, true],
	["Heroku", true, true],
	["Netlify", true, true],
	["AWS", false, false],
	["Jira", true, false],
	["Splunk", false, false],
	["Redash", false, false],
	["Trello", true, false],
	["Twilio", true, false],
	["Sendgrid", true, false],
	["Postman", true, true],
	["EmailJS", false, false],
	["Vite", true, false],
	["REST", true, true],
	["Agile", true, true],
	["Scrum", false, false],
	["UI/UX", false, false],
	["OOP", true, false],
	["TDD", false, false],
	["Jest", false, false],
	["Cypress", false, false],
	["Knex", false, false],
	["Objection", false, false],
	["TypeORM", true, false],
	["Prisma", false, false],
	["Cheerio", false, false],
	["Axios", true, false],
	["Linux", true, false],
	["Windows", true, false],
	["Mac", true, false],
	["Microsoft Office", false, false],
	["Google Suite", false, false],
	["VS Code", true, false],
	["VIM", false, false],
	["Mac/Linux Terminal", true, false],
	["PowerShell", false, false],
]
